name: CI - API and UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install Docker Compose (if missing)
        run: |
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

      - name: Start Selenium Grid
        run: docker-compose up -d

      - name: Wait for Selenium Grid
        run: |
          echo "Waiting for Selenium Grid to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:4444/status | grep '"ready": true'; then
              echo "Selenium Grid is ready!"
              exit 0
            fi
            echo "Waiting for 5 seconds..."
            sleep 5
          done
          echo "Selenium Grid failed to start"
          exit 1

  api-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run API Tests
        run: mvn test -P api-tests

  ui-tests-firefox:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run UI Tests in Firefox
        run: mvn test -Dui.test.browser=firefox -P ui-tests

  ui-tests-chrome:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run UI Tests in Chrome
        run: mvn test -Dui.test.browser=chrome -P ui-tests

  cleanup:
    needs: [api-tests, ui-tests-firefox, ui-tests-chrome]
    runs-on: ubuntu-latest
    steps:
      - name: Stop Selenium Grid
        run: docker-compose down

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/
